#!/bin/sh

curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/arg -o argentina.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/aus -o australia.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/bel -o belgium.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/bra -o brazil.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/col -o colombia.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/crc -o costa-rica.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/cro -o croatia.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/den -o denmark.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/egy -o egypt.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/eng -o england.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/fra -o france.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/ger -o germany.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/isl -o iceland.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/irn -o iran.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/jpn -o japan.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/kor -o korea.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/mex -o mexico.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/mar -o morocco.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/nga -o nigeria.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/pan -o panama.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/per -o peru.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/pol -o poland.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/por -o portugal.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/rus -o russia.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/ksa -o saudi-arabia.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/sen -o senegal.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/srb -o serbia.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/esp -o spain.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/swe -o sweden.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/sui -o switzerland.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/tun -o tunisia.png
curl https://api.fifa.com/api/v1/picture/flags-fwc2018-2/uru -o uruguay.png
